export enum Size {
    "12px" = "12px",
    "16px" = "16px",
    "24px" = "24px",
}

export enum Color {
    "alert300" = "alert300",
    "alert200" = "alert200",
    "alert100" = "alert100",
    "alert050" = "alert050",

    "warning300" = "warning300",
    "warning200" = "warning200",
    "warning100" = "warning100",

    "info300" = "info300",
    "info200" = "info200",
    "info100" = "info100",

    "success800" = "success800",
    "success300" = "success300",
    "success200" = "success200",
    "success100" = "success100",

    "primary-black" = "primary-black",
    "grey400" = "grey400",
    "grey300" = "grey300",
    "grey200" = "grey200",
    "grey100" = "grey100",
    "grey050" = "grey050",
    "white" = "white",

    "primary-surface" = "primary-surface",
    "surface400" = "surface400",
    "surface300" = "surface300",
    "surface200" = "surface200",
    "surface100" = "surface100",

    "orange800" = "orange800",
    "orange700" = "orange700",
    "orange600" = "orange600",
    "primary-orange" = "primary-orange",
    "orange400" = "orange400",
    "orange300" = "orange300",
    "orange200" = "orange200",
    "orange100" = "orange100",

    "blue800" = "blue800",
    "blue700" = "blue700",
    "blue600" = "blue600",
    "primary-blue" = "primary-blue",
    "blue400" = "blue400",
    "blue300" = "blue300",
    "blue200" = "blue200",
    "blue100" = "blue100",
    "blue050" = "blue050",

    "green500" = "green500",
}

// Currently icons are not available in every size
export enum Name {
    "arrow-down" = "arrow-down",
    "arrow-left" = "arrow-left",
    "arrow-right" = "arrow-right",
    "arrow-up" = "arrow-up",
    "calendar" = "calendar",
    "check" = "check",
    "check-circle" = "check-circle",
    "chevron-down-line" = "chevron-down-line",
    "chevron-left-line" = "chevron-left-line",
    "chevron-right-line" = "chevron-right-line",
    "chevron-up-line" = "chevron-up-line",
    "close" = "close",
    "euros" = "euros",
    "minus" = "minus",
    "plus" = "plus",
    "search" = "search",
    "help" = "help",
    "see" = "see",
    "cancel" = "cancel",
    "duplicate" = "duplicate",
    "save" = "save",
    "export-csv" = "export-csv",
    "mail" = "mail",
    "file-invoice-dollar-solid" = "file-invoice-dollar-solid",
    "building" = "building",
    "cash" = "cash",
    "download" = "download",
    "file" = "file",
    "pencil" = "pencil",
    "printer" = "printer",
    "profile" = "profile",
    "share" = "share",
    "shopping-bag" = "shopping-bag",
    "time" = "time",
    "trash" = "trash",
    "warning" = "warning",
    "dashboard" = "dashboard",
    "clients" = "clients",
    "loggout" = "loggout",
}
